package ru.yurch.engflow.service;
import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.test.context.ActiveProfiles;import org.springframework.transaction.annotation.Transactional;import ru.yurch.engflow.model.*;import ru.yurch.engflow.repository.*;import java.util.Set;import static org.assertj.core.api.Assertions.*;
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.NONE) @ActiveProfiles("test") @Transactional
class ItemSupplierServiceTest{
 @Autowired ItemSupplierService service;@Autowired CatalogItemRepository catalogItems;@Autowired OrganizationRepository organizations;
 @Test void managesMultipleSuppliersAndPreservesRelatedEntities(){CatalogItem item=item();Organization first=organization("Поставщик 1",Set.of(OrganizationRole.SUPPLIER));Organization second=organization("Поставщик 2",Set.of(OrganizationRole.SUPPLIER));ItemSupplier relation=new ItemSupplier();relation.setSupplier(first);relation=service.create(item.getId(),relation);ItemSupplier another=new ItemSupplier();another.setSupplier(second);service.create(item.getId(),another);assertThat(service.findByCatalogItem(item.getId())).hasSize(2);assertThat(relation.getSupplierArticle()).isNull();service.delete(item.getId(),relation.getId());assertThat(catalogItems.existsById(item.getId())).isTrue();assertThat(organizations.existsById(first.getId())).isTrue();}
 @Test void rejectsDuplicateAndCustomerOnlyOrganization(){CatalogItem item=item();Organization supplier=organization("Поставщик",Set.of(OrganizationRole.SUPPLIER));ItemSupplier first=new ItemSupplier();first.setSupplier(supplier);service.create(item.getId(),first);ItemSupplier duplicate=new ItemSupplier();duplicate.setSupplier(supplier);assertThatThrownBy(()->service.create(item.getId(),duplicate)).hasMessageContaining("уже добавлен");Organization customer=organization("Заказчик",Set.of(OrganizationRole.CUSTOMER));ItemSupplier invalid=new ItemSupplier();invalid.setSupplier(customer);assertThatThrownBy(()->service.create(item.getId(),invalid)).hasMessageContaining("роли поставщика");}
 private CatalogItem item(){CatalogItem value=new CatalogItem();value.setName("Изделие");value.setUnit("шт.");return catalogItems.save(value);}private Organization organization(String name,Set<OrganizationRole> roles){Organization value=new Organization();value.setName(name);value.setRoles(roles);return organizations.save(value);}
}
