package ru.yurch.engflow.service;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;
import org.springframework.transaction.annotation.Transactional;
import ru.yurch.engflow.model.*;
import ru.yurch.engflow.repository.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Set;
import static org.assertj.core.api.Assertions.*;

@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.NONE)
@ActiveProfiles("test") @Transactional
@TestPropertySource(properties={"engflow.invoice-storage=target/test-invoices","spring.datasource.url=jdbc:h2:mem:eng_flow_procurement;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE"})
class ProcurementServiceTest {
    @Autowired ProcurementService procurements;@Autowired SupplierInvoiceService invoices;@Autowired ProjectRepository projects;@Autowired OrganizationRepository organizations;@Autowired CatalogItemRepository catalogItems;@Autowired MeasurementUnitRepository units;@Autowired ProjectItemRepository projectItems;

    @Test void projectSupportsMultipleProcurementsAndItemCanUseTwoSuppliers(){Project project=project("ИТ901");ProjectItem item=item(project,"Клапан","12");Procurement first=procurement(project,supplier("A"));Procurement second=procurement(project,supplier("B"));addLine(first,item,"2");addLine(second,item,"10");assertThat(procurements.findByProject(project.getId())).hasSize(2);assertThat(procurements.lines(first.getId())).hasSize(1);assertThat(procurements.progress(item).requestedQuantity()).isEqualByComparingTo("12");}

    @Test void rfqAndPaymentFactsDetermineStatusAndAggregateAcrossSuppliers(){Project project=project("ИТ902");ProjectItem item=item(project,"Датчик","12");assertThat(procurements.progress(item).status()).isEqualTo(ProcurementStatus.NOT_REQUESTED);Procurement first=procurement(project,supplier("A"));Procurement second=procurement(project,supplier("B"));ProcurementLine firstLine=addLine(first,item,"2");ProcurementLine secondLine=addLine(second,item,"10");procurements.markRfqSent(project.getId(),first.getId());assertThat(procurements.progress(item).status()).isEqualTo(ProcurementStatus.RFQ_SENT);SupplierInvoice paid=invoice(project,first,"100");addInvoiceLine(project,first,paid,firstLine,"2");SupplierInvoice pending=invoice(project,second,"101");addInvoiceLine(project,second,pending,secondLine,"10");assertThat(procurements.progress(item).status()).isEqualTo(ProcurementStatus.RFQ_SENT);invoices.submitForPayment(project.getId(),first.getId(),paid.getId());ProcurementProgress progress=procurements.progress(item);assertThat(progress.status()).isEqualTo(ProcurementStatus.ORDER_PLACED);assertThat(progress.orderedQuantity()).isEqualByComparingTo("2");assertThat(progress.getDisplay()).isEqualTo("2 / 12 заказано");invoices.submitForPayment(project.getId(),second.getId(),pending.getId());assertThat(procurements.progress(item).orderedQuantity()).isEqualByComparingTo("12");}

    @Test void procurementLineCanSplitAcrossInvoicesButCannotExceedRequested(){Project project=project("ИТ903");ProjectItem item=item(project,"Труба","10");Procurement procurement=procurement(project,supplier("A"));ProcurementLine line=addLine(procurement,item,"10");SupplierInvoice first=invoice(project,procurement,"100");SupplierInvoice second=invoice(project,procurement,"101");addInvoiceLine(project,procurement,first,line,"4");addInvoiceLine(project,procurement,second,line,"6");SupplierInvoice third=invoice(project,procurement,"102");assertThatThrownBy(()->addInvoiceLine(project,procurement,third,line,"1")).hasMessageContaining("превышает");}

    @Test void invoiceCanContainMultipleProcurementLines(){Project project=project("ИТ904");ProjectItem first=item(project,"Клапан","3");ProjectItem second=item(project,"Штуцер","4");Procurement procurement=procurement(project,supplier("A"));ProcurementLine firstLine=addLine(procurement,first,"3");ProcurementLine secondLine=addLine(procurement,second,"4");SupplierInvoice invoice=invoice(project,procurement,"200");addInvoiceLine(project,procurement,invoice,firstLine,"3");addInvoiceLine(project,procurement,invoice,secondLine,"4");assertThat(invoices.lines(invoice.getId())).hasSize(2);}

    @Test void rejectsWrongSupplierProjectAndProcurementReferences(){Project firstProject=project("ИТ905");Project secondProject=project("ИТ906");ProjectItem foreign=item(secondProject,"Чужая позиция","1");Procurement invalid=new Procurement();Organization customer=supplier("Заказчик");customer.getRoles().clear();customer.getRoles().add(OrganizationRole.CUSTOMER);organizations.save(customer);invalid.setSupplier(customer);assertThatThrownBy(()->procurements.create(firstProject.getId(),invalid)).hasMessageContaining("роли поставщика");Procurement first=procurement(firstProject,supplier("A"));ProcurementLine foreignLine=new ProcurementLine();foreignLine.setProjectItem(foreign);foreignLine.setRequestedQuantity(BigDecimal.ONE);assertThatThrownBy(()->procurements.addLine(firstProject.getId(),first.getId(),foreignLine)).hasMessageContaining("не найдена");ProjectItem local=item(firstProject,"Своя позиция","2");ProcurementLine localLine=addLine(first,local,"2");Procurement other=procurement(firstProject,supplier("B"));SupplierInvoice otherInvoice=invoice(firstProject,other,"300");SupplierInvoiceLine wrong=new SupplierInvoiceLine();wrong.setProcurementLine(localLine);wrong.setQuantity(BigDecimal.ONE);assertThatThrownBy(()->invoices.addLine(firstProject.getId(),other.getId(),otherInvoice.getId(),wrong)).hasMessageContaining("не принадлежит");}

    @Test void invoiceFileIsStoredReadableReplaceableAndRemovable(){Project project=project("ИТ907");Procurement procurement=procurement(project,supplier("A"));SupplierInvoice value=new SupplierInvoice();value.setInvoiceNumber("400");value.setInvoiceDate(LocalDate.now());MockMultipartFile file=new MockMultipartFile("file","invoice.pdf","application/pdf","pdf-data".getBytes());SupplierInvoice saved=invoices.create(project.getId(),procurement.getId(),value,file);assertThat(saved.getFileOriginalName()).isEqualTo("invoice.pdf");assertThat(invoices.file(project.getId(),procurement.getId(),saved.getId()).exists()).isTrue();SupplierInvoice update=new SupplierInvoice();update.setInvoiceNumber(saved.getInvoiceNumber());update.setInvoiceDate(saved.getInvoiceDate());MockMultipartFile replacement=new MockMultipartFile("file","replacement.png","image/png","image-data".getBytes());invoices.update(project.getId(),procurement.getId(),saved.getId(),update,replacement);assertThat(invoices.find(project.getId(),procurement.getId(),saved.getId()).getFileOriginalName()).isEqualTo("replacement.png");invoices.deleteFile(project.getId(),procurement.getId(),saved.getId());assertThat(invoices.find(project.getId(),procurement.getId(),saved.getId()).hasFile()).isFalse();}

    private Project project(String designation){Project value=new Project();value.setDesignation(designation);value.setName("Проект");return projects.save(value);}
    private Organization supplier(String name){Organization value=new Organization();value.setName(name);value.getRoles().add(OrganizationRole.SUPPLIER);return organizations.save(value);}
    private ProjectItem item(Project project,String name,String quantity){CatalogItem catalog=new CatalogItem();catalog.setName(name);catalog.setMeasurementUnit(units.findByName("шт.").orElseThrow());catalog=catalogItems.save(catalog);ProjectItem item=new ProjectItem();item.setProject(project);item.setCatalogItem(catalog);ProjectItemAllocation allocation=new ProjectItemAllocation();allocation.setProjectItem(item);allocation.setQuantity(new BigDecimal(quantity));item.getAllocations().add(allocation);return projectItems.save(item);}
    private Procurement procurement(Project project,Organization supplier){Procurement value=new Procurement();value.setSupplier(supplier);return procurements.create(project.getId(),value);}
    private ProcurementLine addLine(Procurement procurement,ProjectItem item,String quantity){ProcurementLine line=new ProcurementLine();line.setProjectItem(item);line.setRequestedQuantity(new BigDecimal(quantity));return procurements.addLine(procurement.getProject().getId(),procurement.getId(),line);}
    private SupplierInvoice invoice(Project project,Procurement procurement,String number){SupplierInvoice value=new SupplierInvoice();value.setInvoiceNumber(number);value.setInvoiceDate(LocalDate.now());return invoices.create(project.getId(),procurement.getId(),value,null);}
    private SupplierInvoiceLine addInvoiceLine(Project project,Procurement procurement,SupplierInvoice invoice,ProcurementLine procurementLine,String quantity){SupplierInvoiceLine line=new SupplierInvoiceLine();line.setProcurementLine(procurementLine);line.setQuantity(new BigDecimal(quantity));return invoices.addLine(project.getId(),procurement.getId(),invoice.getId(),line);}
}
